### ISSUE TITLE
[QUESTION] Duplicated alerts for multiple rules severity

### ISSUE THREAD

**Issue by aishvaryaps** [claranet/terraform-signalfx-detectors#255]
Hi @xp-1000 

Hope you are doing great
This is regarding your comment on Splunk ideas:
https://ideas.splunk.com/ideas/SFXIMMID-I-43
I saw your comment which redirected me to this github repo. You mentioned to create detector referring to below github link:
modules/smart-agent_system-common/detectors-gen.tf - line 24

as per the **detectors-gen.tf** I created detector with below SignalFlow:
A = data('cpu.utilization',filter=filter('host','ip-172-11-11-111.ec2.internal')).publish(label='A')
detect(when(A > 90)).publish('Multi_Detectors-Major')
detect(when(A > 70) and when(A <= 90)).publish('Multi_Detectors-Minor')

I still see two rules created under 1 detector which when trigged creates multiple incident IDs.
Can you please let me know if the SignalfFlow rule I have written is correct / it needs any update?

![image](https://user-images.githubusercontent.com/48279639/110743216-b084e180-825d-11eb-878e-b3dbf60f0351.png)

I am creating detectors using APIs.
Below is the command I have used to create detector:

curl POST 'https://api.us1.signalfx.com/v2/detector' \
--header 'X-SF-TOKEN: <sfx-token>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "Multi Detectors test",
    "programText": "A = data('\''cpu.utilization'\'',filter=filter('\''host'\'','\''ip-172-31-42-120.ec2.internal'\'')).publish(label='\''A'\'')\ndetect(when(A > 50)).publish('\''Multi_Detectors-Major'\'')\ndetect(when(A > 2) and when(A <= 50)).publish('\''Multi_Detectors-Minor'\'')",
    "minDelay":"3000",
    "rules": [
        {
            "description": "Multi_Detectors-Major",
            "detectLabel": "Multi_Detectors-Major",
            "disabled": false,
            "notifications": [
                {
                    "email": "a.suryawanshi@accenture.com",
                    "type": "Email"
                }
            ],
            "severity": "Major"
        },
        {
            "description": "Multi_Detectors-Minor",
            "detectLabel": "Multi_Detectors-Minor",
            "disabled": false,
            "notifications": [
                {
                    "email": "aaaa@a.com",
                    "type": "Email"
                }
            ],
            "severity": "Minor"
        }
    ]
}'

**Comment by xp-1000** [comment]
Hello @aishvaryaps,

I just read again your splunk idea and I am afraid I misread it the first time ..

The workaround I propose and I point here is to create "artificial" dependency between 2 different alerting rules into the same detector.

It will allow to have only once triggered alert maximum at a time.
But it does not prevent to trigger a new event for each alerting rule / threshold.

taking your example:

```
A = data('cpu.utilization',filter=filter('host','ip-172-11-11-111.ec2.internal')).publish(label='A')
detect(when(A > 90)).publish('Multi_Detectors-Major')
detect(when(A > 70) and when(A <= 90)).publish('Multi_Detectors-Minor')
```

minor and major rules cannot be triggered in the same time so there are not "duplicated" alerts because if one triggers the other one resolves.

```
A = data('cpu.utilization',filter=filter('host','ip-172-11-11-111.ec2.internal')).publish(label='A')
detect(when(A > 90)).publish('Multi_Detectors-Major')
detect(when(A > 70)).publish('Multi_Detectors-Minor')
```

it still seems better than this program which will trigger 2 alerts in the same time if value is > 90 which is a redundant information.

sorry for my misunderstanding but I don't know any way to prevent to trigger a new event each time you pass from one alert to another one.

I hope this will, at least, fix the confusion that I brought.

**Comment by aishvaryaps** [comment]
Hi @xp-1000

Not a problem. I am clear what your workaround was meant for.
Thank you very much for the prompt reply.
